name: I18n Updates

on: [push]

jobs:
  apidoc:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - uses: technote-space/get-diff-action@v4
      with:
        PATTERNS: |
          website/common/locales/**/**.json
    - run: node ./.github/i18n.js
      if: env.MATCHED_FILES
